apps/data_plot/urls.py
from django.urls import path
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from . import views

app_name = 'plot'

urlpatterns = [
    path('donnees/', cache_page(None)
         (views.DashboardPlotView.as_view()), name='dashboard'),
    path('', views.PresentationPlotView.as_view(), name='presentation')
]

apps/portal/urls.py
# coding: utf-8

from django.urls import include, path
from .views import MethologyView, RessouresView, HomeView , maintenance

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('methodologie/', MethologyView.as_view(), name="methodologie"),
    path('ressources/', RessouresView.as_view(), name="ressources"),
    path('maintenance/', maintenance, name="maintenance"),
]

ncbif/urls.py
# coding: utf-8

"""ncbif URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from restapi.views import TaxonViewSet, OccurrenceViewSet, \
    PlantnoteDatabaseViewSet


router = routers.DefaultRouter()
router.register(
    r'{}'.format(TaxonViewSet.base_name),
    TaxonViewSet,
    base_name=TaxonViewSet.base_name,

)
router.register(
    r'{}'.format(OccurrenceViewSet.base_name),
    OccurrenceViewSet,
    base_name=OccurrenceViewSet.base_name,
)
router.register(
    r'{}'.format(PlantnoteDatabaseViewSet.base_name),
    PlantnoteDatabaseViewSet,
    base_name=PlantnoteDatabaseViewSet.base_name,
)


urlpatterns = [
    url(r'^{}/'.format(settings.REST_API_BASE_URL), include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

niamoto_portal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from apps.portal import views
from apps.data_plot import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.portal.urls')),
    path('peuplement/', include('apps.data_plot.urls', namespace='plot')),
    path('forets/', include('apps.data_shape.urls', namespace='shape')),
    path('arbres/', include('apps.data_taxon.urls', namespace='taxon')),
    path(f'{settings.REST_API_BASE_URL}/', include('apps.api_rest.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/portal/models.py
from django.db import models
import datetime
# Create your models here.


def current_year():
    return datetime.date.today().year


def year_choicies(year_fisrt):
    return [(r, r) for r in range(year_fisrt, datetime.date.today().year+1)]


class Ressource(models.Model):
    """Model definition for Ressource."""

    SUPPORT = (
        ('publication', 'publication'),
        ('ouvrage', 'livre'),
        ('rapport', 'rapport'),
        ('article', 'article'),
        ('conférence', 'conférence'),
        ('film', 'film'),
        ('radio', 'radio'),
        ('thèse', 'thèse'),
        ('mémoire', 'mémoire')
    )

    support = models.CharField(
        max_length=50, choices=SUPPORT, default='publication')
    who = models.CharField(null=True, blank=True, max_length=400)
    description = models.CharField(null=True, blank=True, max_length=400)
    category = models.CharField(max_length=50, default='divers')
    journal = models.CharField(null=True, blank=True, max_length=250)
    issue = models.CharField(null=True, blank=True, max_length=20)
    pages = models.CharField(null=True, blank=True, max_length=12)
    year = models.IntegerField(
        null=True, blank=True, choices=year_choicies(2012), default=current_year())
    link = models.URLField(null=True, blank=True, max_length=200)


    class Meta:
        """Meta definition for Ressource."""

        verbose_name = 'Ressource'
        verbose_name_plural = 'Ressources'

    def __str__(self):
        """Unicode representation of Ressource."""
        return self.support


class Person(models.Model):
    """Model definition for Person"""

    first_name = models.CharField(null=True, blank=True, max_length=50)
    last_name = models.CharField(null=True, blank=True, max_length=50)
    image = models.ImageField(null=True, blank=True, upload_to='persons',
                              height_field=None, width_field=None, max_length=None)
    permanent = models.BooleanField(null=True, blank=True)
    function = models.CharField(null=True, blank=True, max_length=50)
    speciality = models.CharField(null=True, blank=True, max_length=400)

    class Meta:
        """Meta definition for Person"""

        verbose_name = 'Person'
        verbose_name_plural = 'Persons'

    def __str__(self):
        """Unicode representation of Person"""
        return self.last_name + ' ' + self.first_name


class Activity(models.Model):
    """Model definition for acivity."""

    MONTH = (
        (1, 'janvier'),
        (2, 'février'),
        (3, 'mars'),
        (4, 'avril'),
        (5, 'mai'),
        (6, 'juin'),
        (7, 'juillet'),
        (8, 'aout'),
        (9, 'septembre'),
        (10, 'octobre'),
        (11, 'novembre'),
        (12, 'décembre')
    )

    SUPPORT = (
        ('thèse', 'thèse'),
        ('mémoire', 'mémoire')
    )

    person = models.ForeignKey(
        Person, related_name='activities', on_delete=models.DO_NOTHING)
    contrat = models.CharField(max_length=50)
    first_year = models.IntegerField(
        null=True, blank=True, choices=year_choicies(2010), default=current_year())
    first_month = models.IntegerField(null=True, blank=True, choices=MONTH)
    last_year = models.IntegerField(
        null=True, blank=True, choices=year_choicies(2010), default=current_year())
    last_month = models.IntegerField(null=True, blank=True, choices=MONTH)
    title = models.CharField(null=True, blank=True,
                             max_length=210, default='.')
    support = models.CharField(
        null=True, blank=True, max_length=50, choices=SUPPORT)
    comment = models.CharField(null=True, blank=True, max_length=100)
    description = models.CharField(null=True, blank=True, max_length=850)
    link = models.URLField(null=True, blank=True, max_length=200)

    class Meta:
        """Meta definition for acivity."""

        verbose_name = 'acivity'
        verbose_name_plural = 'activities'

    def __str__(self):
        """Unicode representation of acivity."""
        return self.contrat + ': ' + self.title


class Tree(models.Model):
    """Tree

    Arguments:
        models {[type]} -- [description]
    """

    id_endemia = models.IntegerField(null=True, blank=True)
    id_florical = models.IntegerField(null=True, blank=True)
    family_name = models.CharField(null=True, blank=True, max_length=50)
    genus_name = models.CharField(null=True, blank=True, max_length=50)
    species_name = models.CharField(null=True, blank=True, max_length=150)
    infraspecies_name = models.CharField(null=True, blank=True, max_length=150)
    name = models.CharField(null=True, blank=True, max_length=250)
    statut = models.CharField(null=True, blank=True, max_length=10)

    def __str__(self):
        return

    def __unicode__(self):
        return


class Faq(models.Model):
    """FAQ

    Arguments:
        models {[type]} -- [description]
    """

    question = models.CharField(max_length=200, default="")
    ask = models.CharField(max_length=1500, default="")

    def __str__(self):
        return 

    def __unicode__(self):
        return 

class SiteInfo(models.Model):
    """SiteInfo
    class permitting the storage of general site data

    Args:
        models ([type]): [description]
    """
    
    dateUpdateData = models.DateField()


    def __str__(self):
        return 

    def __unicode__(self):
        return 

apps/portal/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.template import loader
from .models import Ressource, Person, Activity, Tree, Faq, SiteInfo
import random
# Create your views here.


class HomeView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, **kwargs):
        siteInfos = SiteInfo.objects.all()
        return {
            'siteinfos': siteInfos
        }


def maintenance(request):
    return render(request, 'maintenance.html', {})


# def ressources(request):
#     return render(request, 'ressources.html', {})


class RessouresView(TemplateView):

    template_name = 'ressources.html'

    def get_context_data(self, **kwargs):
        ressources = Ressource.objects.all().order_by('-year')
        persons = Person.objects.all().order_by('?')
        activities = Activity.objects.all
        trees = Tree.objects.all().order_by(
            'family_name', 'genus_name', 'name')
        siteInfos = SiteInfo.objects.all()
        return {
            'ressources': ressources,
            'persons': persons,
            'activities': activities,
            'trees': trees,
            'siteinfos': siteInfos
        }

class MethologyView(TemplateView):
    template_name= 'methodologie.html'

    def get_context_data(self, **kwargs):
        faqs = Faq.objects.all().order_by('id')
        siteInfos = SiteInfo.objects.all()
        return {
            'faqs': faqs,
            'siteinfos': siteInfos
        }
    

apps/portal/templates/_base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
  <meta charset="utf-8" />
  <title>{% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }}
    | {% endif %}{% block head_title %}{% endblock head_title %}{% endblock head_title_base %}</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  {% block viewport %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% endblock %}
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" />


  {% block styles %}
  {% include "_style.html" %}
  {% endblock styles %}

  {% block html5shim %}
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
                <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
            <![endif]-->
  {% endblock html5shim%}


  {% block extra_head_base %}
  {% block extra_head %}{% endblock extra_head%}
  {% endblock extra_head_base%}
</head>


<!-- Navigation -->
{% include "_nav.html" %}

{% block page_header %}
{% endblock page_header %}

{% block body %}
{% endblock body %}





{% include "_footer.html" %}

{% block extra_body %}
{% endblock extra_body %}


{% block scripts %}
{% include "_scripts.html" %}
{% endblock scripts%}



</body>

</html>

apps/portal/templates/_footer.html
{% load staticfiles %}
<footer class="">
  <div class="container">
    <div class="logos row">
      <div class="col-12 col-sm-12 col-md-4 col-lg-5 d-flex"><a class='logo' href="https://www.province-nord.nc/"
          target="_blank">
          <figure>
            <img id=pn class="img-fluid" src="{% static 'img/logo/pn_100.png' %}">
          </figure>
        </a>
        <a class='logo' href="http://amap.cirad.fr/" target="_blank">
          <figure>
            <img id=amap class="img-fluid" src="{% static 'img/logo/amap_100.png' %}">
          </figure>
        </a>
        <a class='logo' href="http://publish.plantnet-project.org/project/nou" target="_blank">
          <figure>
            <img id=herbarium class="img-fluid" src="{% static 'img/logo/herbarium_100.png' %}">
          </figure>
        </a>
      </div>
      <div class="col-1 col-sm-0 col-lg-1"></div>
      <div class="col-12 col-sm-12 col-md-7 col-lg-6 d-flex">
        <a class='logo' href="http://iac.nc/" target="_blank">
          <figure>
            <img id=iac class="img-fluid" src="{% static 'img/logo/iac_100.png' %}">
          </figure>
        </a>
        <a class='logo' href="https://nouvelle-caledonie.ird.fr/" target="_blank">
          <figure>
            <img id=ird class="img-fluid" src="{% static 'img/logo/ird_100.png' %}">
          </figure>
        </a>
        <a class='logo' href="https://cirad.fr/" target="_blank">
          <figure>
            <img id=cirad class="img-fluid" src="{% static 'img/logo/cirad_100.png' %}">
          </figure>
        </a>
      </div>
    </div>
    <div class="row copy">
      <div class="col-md-10">
        <p class="text-right">Niamoto - Portail de la forêt de Nouvelle-Calédonie en Province Nord - AMAP/CIRAD/IRD/IAC
          - Date de mise à jour {{siteinfos.0.dateUpdateData}}</p>
      </div>
      <div class="col-md-2">

        <p class="text-right">
          <a href='https://github.com/niamoto/niamoto-portal' target="_blank">
            <span class="fab fa-github fa-lg" aria-hidden="true"></span>
          </a> Github
        </p>
      </div>
    </div>
  </div>
</footer>

apps/portal/templates/_nav.html
{% load staticfiles %}
<nav id="navbar" class="navbar-expand-md navbar-dark  btco-hover-menu bg-bandeau-default fixed-top">
  <div id="mainNav" class="d-flex">

    

    
    <div class="collapse navbar-collapse justify-content-md-center align-self-start" id="navbarNavDropdown">
      
      <ul class="navbar-nav">
        <div class="p-2 navbar-brand">Niamoto</div>
        <li class="nav-item dropdown text-lowercase">
          <a class="nav-link " href="{% url 'home' %}" id="navbarDropdownMenuLink" aria-haspopup="true"
            aria-expanded="false">
            Accueil</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item text-lowercase" href="{% url 'home' %}#introduction">Introduction</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'home' %}#project">Projet</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'home' %}#objective">Objectifs</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'home' %}#context">Contexte</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'home' %}#flora">Flore</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown text-lowercase">
          <a class="nav-link " href="{% url 'methodologie' %}" id="navbarDropdownMenuLink" aria-haspopup="true"
            aria-expanded="false">Méthodologie</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item text-lowercase" href="{% url 'methodologie' %}#preambule">Préambule</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'methodologie' %}#methodes">Nos méthodes</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'methodologie' %}#faq">Questions/réponses</a>
            </li>
          </ul>
        </li>

        <li class="nav-item dropdown text-lowercase">
          <a class="nav-link " href="{% url 'taxon:presentation' %}" aria-haspopup="true"
            aria-expanded="false">Arbres</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item text-lowercase" href="{% url 'taxon:presentation' %}#preambule">Préambule</a>
            </li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'taxon:presentation' %}#learnTaxon">Étudier les
                arbres</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'taxon:presentation' %}#taxon">Les arbres de
                Nouvelle-Calédonie</a>
            </li>
          </ul>
        </li>

        <li class="nav-item dropdown text-lowercase">
          <a class="nav-link " href="{% url 'plot:presentation' %}" aria-haspopup="true"
            aria-expanded="false">Peuplements</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item text-lowercase" href="{% url 'plot:presentation' %}#preambule">Préambule</a>
            </li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'plot:presentation' %}#learnPlot">Étudier les
                peuplements
                forestiers</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'plot:presentation' %}#plot">Les
                peuplements forestiers de Nouvelle-Calédonie</a>
            </li>
          </ul>
        </li>

        <li class="nav-item dropdown text-lowercase">
          <a class="nav-link " href="{% url 'shape:presentation' %}" id=" navbarDropdownMenuLink" aria-haspopup="true"
            aria-expanded="false">Forêt</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item text-lowercase" href="{% url 'shape:presentation' %}#preambule">Préambule</a>
            </li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'shape:presentation' %}#learnForest">Étudier les
                forêts</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'shape:presentation' %}#forestPN">La forêt de la
                province Nord</a>
            </li>
          </ul>
        </li>

        <li class="nav-item dropdown text-lowercase">
          <a class="nav-link " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Accéder aux données</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item text-lowercase" href="{% url 'taxon:dashboard' %}">Arbres</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'plot:dashboard' %}">Peuplements</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'shape:dashboard' %}">Forêt</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown text-lowercase">
          <a class="nav-link " href="{% url 'ressources' %}" id="navbarDropdownMenuLink" aria-haspopup="true"
            aria-expanded="false">Ressources</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item text-lowercase" href="{% url 'ressources' %}#equipe">Équipe</a></li>
            <li><a class="dropdown-item text-lowercase" href="{% url 'ressources' %}#production"">Productions</a></li>
            <li><a class=" dropdown-item text-lowercase" href="{% url 'ressources' %}#listTree">Liste des arbres</a>
            </li>
          </ul>
        </li>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div id='logos' class="p-2 d-flex">
      <a class='logo' href="https://www.province-nord.nc/" target="_blank">
        <figure>
          <img class="img-fluid" id=pn_50 src="{% static 'img/logo/pn_50.png' %}">
        </figure>
      </a>
      <a class='logo' href="http://amap.cirad.fr/" target="_blank">
        <figure>
          <img class="img-fluid" id=amap_50 src="{% static 'img/logo/amap_50.png' %}">
        </figure>
      </a>
      <a class='logo' href="http://publish.plantnet-project.org/project/nou" target="_blank">
        <figure>
          <img class="img-fluid" id=herbarium_50 src="{% static 'img/logo/herbarium_50.png' %}">
        </figure>
      </a>      
      <a class='logo' href="http://iac.nc/" target="_blank">
        <figure>
          <img class="img-fluid" id=iac_50 src="{% static 'img/logo/iac_50.png' %}">
        </figure>
      </a>
      <a class='logo' href="https://nouvelle-caledonie.ird.fr/" target="_blank">
        <figure>
          <img class="img-fluid" id=ird_50 src="{% static 'img/logo/ird_50.png' %}">
        </figure>
      </a>
      <a class='logo' href="https://cirad.fr/" target="_blank">
        <figure>
          <img class="img-fluid" id=cirad_50 src="{% static 'img/logo/cirad_50.png' %}">
        </figure>
      </a>
    </div>
  </div>
</nav>

apps/portal/templates/_scripts.html
{% load staticfiles %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
  integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="{% static 'js/main.min.js' %}"></script>

apps/portal/templates/_style.html
{% load staticfiles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato|Nunito+Sans&display=swap">

apps/portal/templates/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
  <meta charset="utf-8" />
  <title>{% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }}
    | {% endif %}{% block head_title %}{% endblock head_title %}{% endblock head_title_base %}</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  {% block viewport %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% endblock %}
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" />


  {% block styles %}
  {% include "_style.html" %}
  {% endblock styles %}

  {% block html5shim %}
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
                <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
            <![endif]-->
  {% endblock html5shim%}


  {% block extra_head_base %}
  {% block extra_head %}{% endblock extra_head%}
  {% endblock extra_head_base%}
</head>


<!-- Navigation -->
{% include "_nav.html" %}

{% block page_header %}
{% endblock page_header %}

{% block body %}
{% endblock body %}





{% include "_footer.html" %}

{% block extra_body %}
{% endblock extra_body %}


{% block scripts %}
{% include "_scripts.html" %}
{% endblock scripts%}



</body>

</html>

apps/portal/templates/maintenance.html
<!doctype html>
<html lang="fr">
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <title>Serveur en maintenance</title>
    <link rel="stylesheet" href="{% static 'css/maintenance.css' %}">

</head>

<body>


    <h1>Site en maintenance</h1>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>

    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
</body>

</html>